    /**
     * @description       : 
     * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
     * @group             : 
     * @last modified on  : 05-06-2024
     * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
    **/
    /**
     * @description       : Classe utilitaire pour générer des données de test dans Salesforce.
     * @author            : [Ton nom ou pseudo]
     * @group             : [Nom du groupe de travail]
     * @last modified on  : 05-06-2024
     * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
    **/
    @isTest
    public with sharing class TestDataFactory {

        //methode pour créer une order line item
Integer numItemsPerOrder = 5; // Replace 5 with the desired number of items per order